import json
import logging
from typing import List

from src.core.schema import (
    Message, Role, ModelConfig, GenerationResult,
    UncertaintyReport, UncertaintyAction
)
from src.core.model import generate_response

logger = logging.getLogger(__name__)

ANALYZER_PROMPT = """You are the uncertainty controller for an AI reasoning pipeline.

Given the user query, the conversation context, and the candidate answers generated by different reasoning roles:
Do not solve the task directly. Analyze the uncertainty and return ONLY valid JSON.

Classify uncertainty into the following flags if they apply:
- intent_ambiguity (User intent is unclear)
- missing_context (Missing project context/rules)
- factual_uncertainty (Needs web/external facts)
- logical_conflict (Candidates disagree logically)
- computational_verifiability (Can be tested via code)
- safety_or_permission_risk (Modifies system state or needs permission)

For each conflict or unknown, specify its severity (low, medium, high) and whether it can be resolved by asking the user, researching, or verifying with a tool.

You MUST output exactly this JSON structure (no markdown fences, no extra text):
{
  "total_score": 0.5,
  "semantic_agreement": 0.8,
  "claim_conflicts": [
    {
      "claim_a": "...",
      "claim_b": "...",
      "conflict_type": "...",
      "severity": "low|medium|high"
    }
  ],
  "unknowns": [
    {
      "description": "...",
      "kind": "user_intent|factual|contextual",
      "ask_user": true,
      "researchable": false
    }
  ],
  "assumptions": ["..."],
  "research_questions": ["..."],
  "clarification_questions": ["..."],
  "computable_checks": ["..."],
  "risk_flags": ["..."]
}

CRITICAL: Do NOT include a "recommended_action" field. Only provide the facts above.
"""

# JSON mode hint — supported by both Gemini and Ollama via LiteLLM.
_JSON_RESPONSE_FORMAT = {"type": "json_object"}


def analyze_uncertainty(
    messages: List[Message],
    candidates: List[GenerationResult],
    consistency: float,
    config: ModelConfig
) -> UncertaintyReport:
    """Analyze generated candidates to produce an UncertaintyReport.

    Uses JSON mode to enforce structured output from the LLM.
    Falls back to a safe default report if parsing fails.
    """
    
    unique_ans = "\n\n---\n\n".join(
        f"Candidate {i + 1}:\n{t.content}" for i, t in enumerate(candidates)
    )
    
    analyzer_msg = Message(
        role=Role.USER,
        content=(
            f"{ANALYZER_PROMPT}\n\n"
            f"Semantic agreement score (cosine similarity): {consistency:.2f}\n\n"
            f"CANDIDATES:\n{unique_ans}"
        )
    )
    
    last_user_query = ""
    for m in reversed(messages):
        if m.role == Role.USER:
            last_user_query = m.content
            break
            
    context_msg = Message(
        role=Role.USER,
        content=f"Original Query Context:\n{last_user_query}"
    )
    
    try:
        res = generate_response(
            messages=[context_msg, analyzer_msg],
            model_name=config.model_name,
            temperature=0.1,  # Low temp for structured extraction
            max_tokens=config.max_tokens,
            n=1,
            response_format=_JSON_RESPONSE_FORMAT,
        )[0]
    except Exception as e:
        logger.warning("Analyzer LLM call failed: %s", e)
        return _fallback_report(consistency)
    
    try:
        content = res.content.strip()
        # Belt-and-suspenders: strip markdown fences if model ignores JSON mode
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]

        data = json.loads(content.strip())

        # Remove recommended_action if the LLM smuggled one in anyway —
        # we don't trust it to pick actions.
        data.pop("recommended_action", None)

        report = UncertaintyReport(**data)
        # Override with the actual embedding-based score
        report.semantic_agreement = consistency
        return report
    except Exception as e:
        logger.warning("Failed to parse UncertaintyReport JSON: %s", e)
        return _fallback_report(consistency)


def _fallback_report(consistency: float) -> UncertaintyReport:
    """Build a safe fallback report when the analyzer fails.

    Uses consistency alone: low consistency → adversarial review,
    high consistency → answer directly.
    """
    action = (
        UncertaintyAction.ADVERSARIAL_REVIEW
        if consistency < 0.75
        else UncertaintyAction.ANSWER
    )
    return UncertaintyReport(
        semantic_agreement=consistency,
        total_score=1.0 - consistency,
        recommended_action=action,
    )


def decide_action(report: UncertaintyReport) -> UncertaintyAction:
    """Deterministic rule engine to choose the best action.

    Priority order (highest to lowest):
    1. Safety/permission risk → ASK_USER
    2. User intent ambiguity with clarification questions → ASK_USER
    3. High-severity claim conflicts → ADVERSARIAL_REVIEW
    4. Researchable unknowns with research questions → RESEARCH
    5. Computable checks available → VERIFY_WITH_TOOL
    6. Low uncertainty (score ≤ 0.3 or agreement ≥ 0.85) → ANSWER
    7. Default → ANSWER_WITH_CAVEATS

    The LLM's ``recommended_action`` field is intentionally ignored.
    """
    # PRIORITY 1: Safety risks are always escalated to user
    if report.risk_flags:
        return UncertaintyAction.ASK_USER

    # PRIORITY 2: User intent is unclear — ask for clarification
    if report.clarification_questions and any(
        u.kind == "user_intent" for u in report.unknowns
    ):
        return UncertaintyAction.ASK_USER

    # PRIORITY 3: Researchable questions — external research
    if report.research_questions and any(
        u.researchable for u in report.unknowns
    ):
        return UncertaintyAction.RESEARCH

    # PRIORITY 4: Computationally verifiable — tool verification
    if report.computable_checks:
        return UncertaintyAction.VERIFY_WITH_TOOL

    # PRIORITY 5: High-severity logical conflicts — adversarial review
    if report.claim_conflicts and any(
        c.severity == "high" for c in report.claim_conflicts
    ):
        return UncertaintyAction.ADVERSARIAL_REVIEW

    # PRIORITY 6: Low uncertainty — answer directly
    if report.total_score <= 0.3 or report.semantic_agreement >= 0.85:
        return UncertaintyAction.ANSWER

    # DEFAULT: Medium uncertainty — answer with explicit caveats
    return UncertaintyAction.ANSWER_WITH_CAVEATS
