import json
import logging
from typing import List

from src.core.schema import (
    Message, Role, ModelConfig, GenerationResult,
    UncertaintyReport, UncertaintyAction
)
from src.core.model import generate_response

logger = logging.getLogger(__name__)

ANALYZER_PROMPT = """You are the uncertainty controller for an AI reasoning pipeline.

Given the user query, the conversation context, and the candidate answers generated by different reasoning roles:
Do not solve the task directly. Analyze the uncertainty and return ONLY valid JSON.

Classify uncertainty into the following flags if they apply:
- intent_ambiguity (User intent is unclear)
- missing_context (Missing project context/rules)
- factual_uncertainty (Needs web/external facts)
- logical_conflict (Candidates disagree logically)
- computational_verifiability (Can be tested via code)
- safety_or_permission_risk (Modifies system state or needs permission)
- extrapolation_from_small_sample (Inferring a general formula/theorem from a small toy experiment without formal proof or independent holdout verification)
- target_scale_far_beyond_verified_range (The verified data points are much smaller than the target query scale)
- unproven_sequence_formula (A pattern is hypothesized but lacks a rigorous derivation)
- failed_tool_call (A previous tool call failed, leaving the hypothesis unverified)
- IMPORTANT: Distinguish between 'Solver Errors' and 'User Ambiguity'.
- If a candidate answer makes an assumption that is explicitly contradicted or already defined in the user's prompt (e.g., the user says "alpha: Z -> Z" but a candidate assumes alpha is binary), this is a SOLVER ERROR. Do NOT ask the user for clarification in this case. Instead, mark it as a logical conflict and recommend a computable check or research.
- Only use 'ASK_USER' for true 'User Intent' ambiguity where the prompt is genuinely underspecified.
- If the user explicitly asks you to "research", "experiment", or "use tools" in the history, prioritize 'researchable' or 'computable' over 'ask_user'.

For each conflict or unknown, specify its severity (low, medium, high) and whether it can be resolved by asking the user, researching, or verifying with a tool.

You MUST output exactly this JSON structure (no markdown fences, no extra text):
{
  "total_score": 0.5,
  "semantic_agreement": 0.8,
  "claim_conflicts": [
    {
      "claim_a": "...",
      "claim_b": "...",
      "conflict_type": "...",
      "severity": "low|medium|high"
    }
  ],
  "unknowns": [
    {
      "description": "...",
      "kind": "user_intent|factual|contextual",
      "ask_user": true,
      "researchable": false
    }
  ],
  "assumptions": ["..."],
  "research_questions": ["..."],
  "clarification_questions": ["..."],
  "computable_checks": ["..."],
  "risk_flags": ["..."]
}

CRITICAL: Do NOT include a "recommended_action" field. Only provide the facts above.
"""

# JSON mode hint — supported by both Gemini and Ollama via LiteLLM.
_JSON_RESPONSE_FORMAT = {"type": "json_object"}


def analyze_uncertainty(
    messages: List[Message],
    candidates: List[GenerationResult],
    consistency: float,
    config: ModelConfig
) -> UncertaintyReport:
    """Analyze generated candidates to produce an UncertaintyReport.

    Uses JSON mode to enforce structured output from the LLM.
    Falls back to a safe default report if parsing fails.
    """
    
    unique_ans = "\n\n---\n\n".join(
        f"Candidate {i + 1}:\n{t.content}" for i, t in enumerate(candidates)
    )
    
    analyzer_msg = Message(
        role=Role.USER,
        content=(
            f"{ANALYZER_PROMPT}\n\n"
            f"Semantic agreement score (cosine similarity): {consistency:.2f}\n\n"
            f"CANDIDATES:\n{unique_ans}"
        )
    )
    
    last_user_query = ""
    for m in reversed(messages):
        if m.role == Role.USER:
            last_user_query = m.content
            break
            
    context_msg = Message(
        role=Role.USER,
        content=f"Original Query Context:\n{last_user_query}"
    )
    
    try:
        res = generate_response(
            messages=[context_msg, analyzer_msg],
            model_name=config.model_name,
            temperature=0.1,  # Low temp for structured extraction
            max_tokens=config.max_tokens,
            n=1,
            response_format=_JSON_RESPONSE_FORMAT,
        )[0]
    except Exception as e:
        logger.warning("Analyzer LLM call failed: %s", e)
        return _fallback_report(consistency)
    
    try:
        content = res.content.strip()
        # Belt-and-suspenders: strip markdown fences if model ignores JSON mode
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]

        data = json.loads(content.strip())

        # Remove recommended_action if the LLM smuggled one in anyway —
        # we don't trust it to pick actions.
        data.pop("recommended_action", None)

        report = UncertaintyReport(**data)
        # Override with the actual embedding-based score
        report.semantic_agreement = consistency
        return report
    except Exception as e:
        logger.warning("Failed to parse UncertaintyReport JSON: %s", e)
        return _fallback_report(consistency)


def _fallback_report(consistency: float) -> UncertaintyReport:
    """Build a safe fallback report when the analyzer fails.

    Uses consistency alone: low consistency → adversarial review,
    high consistency → answer directly.
    """
    action = (
        UncertaintyAction.ADVERSARIAL_REVIEW
        if consistency < 0.75
        else UncertaintyAction.ANSWER
    )
    return UncertaintyReport(
        semantic_agreement=consistency,
        total_score=1.0 - consistency,
        recommended_action=action,
    )


def decide_action(report: UncertaintyReport, last_user_message: str = "", is_loop: bool = False) -> UncertaintyAction:
    """Deterministic rule engine to choose the best action.

    Priority order:
    1. Safety/permission risk → ASK_USER
    2. User redirection (explicitly asks for tools/research) → RESEARCH/VERIFY
    3. User intent ambiguity (True Ambiguity) → ASK_USER (unless in loop)
    4. Researchable unknowns → RESEARCH
    5. Computable checks → VERIFY_WITH_TOOL
    6. High-severity logical conflicts → ADVERSARIAL_REVIEW
    7. Low uncertainty → ANSWER
    """
    
    high_conflict = report.claim_conflicts and any(c.severity == "high" for c in report.claim_conflicts)
    has_computable = bool(report.computable_checks)
    has_research = bool(report.research_questions)
    low_score = report.total_score < 0.55

    # HARD RULE 1 & 2: High conflict or low score with tools available MUST use tools
    if (high_conflict or low_score) and has_computable:
        return UncertaintyAction.VERIFY_WITH_TOOL

    if high_conflict and has_research:
        return UncertaintyAction.RESEARCH

    # PRIORITY 1: Safety risks always escalate
    if report.risk_flags and any(f in ["safety_or_permission_risk", "permission_risk"] for f in report.risk_flags):
        return UncertaintyAction.ASK_USER

    # PRIORITY 1.5: Evidence Sufficiency Gate (Premature Extrapolation)
    premature_flags = {"extrapolation_from_small_sample", "unproven_sequence_formula", "target_scale_far_beyond_verified_range"}
    if report.risk_flags and any(f in premature_flags for f in report.risk_flags):
        if has_computable:
            return UncertaintyAction.VERIFY_WITH_TOOL
        return UncertaintyAction.ADVERSARIAL_REVIEW

    # PRIORITY 1.6: Failed Tool Call Fallback
    if report.risk_flags and "failed_tool_call" in report.risk_flags:
        if has_computable:
            return UncertaintyAction.VERIFY_WITH_TOOL
        return UncertaintyAction.ANSWER_WITH_CAVEATS

    # PRIORITY 2: Detect if user is pushing for self-resolution
    redirection_keywords = ["research", "search", "experiment", "toy", "tool", "code", "run", "verify", "check yourself"]
    user_wants_tools = any(kw in last_user_message.lower() for kw in redirection_keywords)
    
    if user_wants_tools:
        if has_computable:
            return UncertaintyAction.VERIFY_WITH_TOOL
        if has_research:
            return UncertaintyAction.RESEARCH

    # PRIORITY 3: True user intent ambiguity
    if not is_loop and report.clarification_questions and any(u.kind == "user_intent" for u in report.unknowns):
        return UncertaintyAction.ASK_USER

    # PRIORITY 4: Research
    if has_research and any(u.researchable for u in report.unknowns):
        return UncertaintyAction.RESEARCH

    # PRIORITY 5: Tools
    if has_computable:
        return UncertaintyAction.VERIFY_WITH_TOOL

    # PRIORITY 6: Low uncertainty
    if not high_conflict and (report.total_score <= 0.3 or report.semantic_agreement >= 0.85):
        return UncertaintyAction.ANSWER

    return UncertaintyAction.ANSWER_WITH_CAVEATS

