import json
import logging
from typing import List

from src.core.schema import (
    Message, Role, ModelConfig, GenerationResult,
    UncertaintyReport, UncertaintyAction
)
from src.core.model import generate_response

logger = logging.getLogger(__name__)

ANALYZER_PROMPT = """You are the uncertainty controller for an AI reasoning pipeline.

Given the user query, the conversation context, and the candidate answers generated by different reasoning roles:
Do not solve the task directly. Analyze the uncertainty and return ONLY valid JSON.

Classify uncertainty into the following flags if they apply:
- intent_ambiguity (User intent is unclear)
- missing_context (Missing project context/rules)
- factual_uncertainty (Needs web/external facts)
- logical_conflict (Candidates disagree logically)
- computational_verifiability (Can be tested via code)
- safety_or_permission_risk (Modifies system state or needs permission)

For each conflict or unknown, specify its severity (low, medium, high) and whether it can be resolved by asking the user, researching, or verifying with a tool.

Then choose EXACTLY ONE recommended_action from this list:
- answer
- answer_with_caveats
- ask_user
- research
- verify_with_tool
- adversarial_review
- refuse_or_defer

Output schema must be exactly this JSON structure:
{
  "total_score": 0.5,
  "semantic_agreement": 0.8,
  "claim_conflicts": [
    {
      "claim_a": "...",
      "claim_b": "...",
      "conflict_type": "...",
      "severity": "low|medium|high"
    }
  ],
  "unknowns": [
    {
      "description": "...",
      "kind": "user_intent|factual|contextual",
      "ask_user": true,
      "researchable": false
    }
  ],
  "assumptions": ["..."],
  "research_questions": ["..."],
  "clarification_questions": ["..."],
  "computable_checks": ["..."],
  "risk_flags": ["..."],
  "recommended_action": "answer"
}
"""

def analyze_uncertainty(
    messages: List[Message],
    candidates: List[GenerationResult],
    consistency: float,
    config: ModelConfig
) -> UncertaintyReport:
    """Analyze generated candidates to produce an UncertaintyReport."""
    
    unique_ans = "\\n\\n---\\n\\n".join(
        f"Candidate {i + 1}:\\n{t.content}" for i, t in enumerate(candidates)
    )
    
    analyzer_msg = Message(
        role=Role.USER,
        content=(
            f"{ANALYZER_PROMPT}\\n\\n"
            f"Semantic agreement score (cosine similarity): {consistency:.2f}\\n\\n"
            f"CANDIDATES:\\n{unique_ans}"
        )
    )
    
    last_user_query = ""
    for m in reversed(messages):
        if m.role == Role.USER:
            last_user_query = m.content
            break
            
    context_msg = Message(
        role=Role.USER,
        content=f"Original Query Context:\\n{last_user_query}"
    )
    
    res = generate_response(
        messages=[context_msg, analyzer_msg],
        model_name=config.model_name,
        temperature=0.1,  # Low temp for structured extraction
        max_tokens=config.max_tokens,
        n=1
    )[0]
    
    try:
        content = res.content.strip()
        if content.startswith("```json"):
            content = content[7:]
        if content.endswith("```"):
            content = content[:-3]
        data = json.loads(content.strip())
        report = UncertaintyReport(**data)
        report.semantic_agreement = consistency
        return report
    except Exception as e:
        logger.warning(f"Failed to parse UncertaintyReport JSON: {e}")
        action = UncertaintyAction.ADVERSARIAL_REVIEW if consistency < 0.75 else UncertaintyAction.ANSWER
        return UncertaintyReport(
            semantic_agreement=consistency,
            total_score=1.0 - consistency,
            recommended_action=action
        )

def decide_action(report: UncertaintyReport) -> UncertaintyAction:
    """Rule-based decision layer to choose the best action."""
    if report.risk_flags:
        return UncertaintyAction.ASK_USER
        
    if report.clarification_questions and any(u.kind == "user_intent" for u in report.unknowns):
        return UncertaintyAction.ASK_USER
        
    if report.research_questions and any(u.researchable for u in report.unknowns):
        return UncertaintyAction.RESEARCH
        
    if report.claim_conflicts and any(c.severity == "high" for c in report.claim_conflicts):
        return UncertaintyAction.ADVERSARIAL_REVIEW
        
    if report.computable_checks:
        return UncertaintyAction.VERIFY_WITH_TOOL
        
    if report.total_score <= 0.3 or report.semantic_agreement >= 0.8:
        return UncertaintyAction.ANSWER
        
    return UncertaintyAction.ANSWER_WITH_CAVEATS
